//
// Copyright (c) https://developers.google.com/
// https://developers.google.com/admin-sdk/directory/v1/languages
//
const AVAILABLE_LANGUAGES = [
	{ code: "af", name: "Afrikaans"},
	{ code: "sq", name: "Albanian"},
	{ code: "ar", name: "Arabic"},
	{ code: "hy", name: "Armenian"},
	{ code: "az", name: "Azerbaijani"},
	{ code: "eu", name: "Basque"},
	{ code: "be", name: "Belarusian"},
	{ code: "bn", name: "Bengali"},
	{ code: "bs", name: "Bosnian (Latin)"},
	{ code: "bg", name: "Bulgarian"},
	{ code: "ca", name: "Catalan"},
	{ code: "ceb", name: "Cebuano"},
	{ code: "zh", name: "Chinese (Simplified)"},
	{ code: "zh-TW", name: "Chinese (Traditional)"},
	{ code: "hr", name: "Croatian"},
	{ code: "cs", name: "Czech"},
	{ code: "da", name: "Danish"},
	{ code: "nl", name: "Dutch"},
	{ code: "en", name: "English"},
	{ code: "eo", name: "Esperanto"},
	{ code: "et", name: "Estonian"},
	{ code: "tl", name: "Filipino"},
	{ code: "fi", name: "Finnish"},
	{ code: "fr", name: "French"},
	{ code: "gl", name: "Galician"},
	{ code: "ka", name: "Georgian"},
	{ code: "de", name: "German"},
	{ code: "el", name: "Greek"},
	{ code: "gu", name: "Gujarati"},
	{ code: "ht", name: "Haitian Creole"},
	{ code: "ha", name: "Hausa"},
	{ code: "iw", name: "Hebrew"},
	{ code: "hi", name: "Hindi"},
	{ code: "hmn", name: "Hmong"},
	{ code: "hu", name: "Hungarian"},
	{ code: "is", name: "Icelandic"},
	{ code: "ig", name: "Igbo"},
	{ code: "id", name: "Indonesian"},
	{ code: "ga", name: "Irish"},
	{ code: "it", name: "Italian"},
	{ code: "ja", name: "Japanese"},
	{ code: "jw", name: "Javanese"},
	{ code: "kn", name: "Kannada"},
	{ code: "km", name: "Khmer"},
	{ code: "ko", name: "Korean"},
	{ code: "lo", name: "Lao"},
	{ code: "la", name: "Latin"},
	{ code: "lv", name: "Latvian"},
	{ code: "lt", name: "Lithuanian"},
	{ code: "mk", name: "Macedonian"},
	{ code: "ms", name: "Malay"},
	{ code: "mt", name: "Maltese"},
	{ code: "mi", name: "Maori"},
	{ code: "mr", name: "Marathi"},
	{ code: "mn", name: "Mongolian"},
	{ code: "ne", name: "Nepali"},
	{ code: "no", name: "Norwegian"},
	{ code: "fa", name: "Persian"},
	{ code: "pl", name: "Polish"},
	{ code: "pt", name: "Portuguese"},
	{ code: "pa", name: "Punjabi"},
	{ code: "ro", name: "Romanian"},
	{ code: "ru", name: "Russian"},
	{ code: "sr", name: "Serbian (Cyrillic)"},
	{ code: "sk", name: "Slovak"},
	{ code: "sl", name: "Slovenian"},
	{ code: "so", name: "Somali"},
	{ code: "es", name: "Spanish"},
	{ code: "sw", name: "Swahili"},
	{ code: "sv", name: "Swedish"},
	{ code: "ta", name: "Tamil"},
	{ code: "te", name: "Telugu"},
	{ code: "th", name: "Thai"},
	{ code: "tr", name: "Turkish"},
	{ code: "uk", name: "Ukrainian"},
	{ code: "ur", name: "Urdu"},
	{ code: "vi", name: "Vietnamese"},
	{ code: "cy", name: "Welsh"},
	{ code: "yi", name: "Yiddish"},
	{ code: "yo", name: "Yoruba"},
	{ code: "zu", name: "Zulu"},
	{ code: "mww", name: "Hmong Daw"},
	{ code: "tlh", name: "Klingon"},
	{ code: "sr-La", name: "Serbian (Latin)"},
	{ code: "am", name: "Amharic"},
	{ code: "ny", name: "Chichewa"},
	{ code: "fy", name: "Frisian"},
	{ code: "haw", name: "Hawaiian"},
	{ code: "kk", name: "Kazakh"},
	{ code: "ku", name: "Kurdish"},
	{ code: "ky", name: "Kyrgyz"},
	{ code: "lb", name: "Luxembourgish"},
	{ code: "mg", name: "Malagasy"},
	{ code: "ml", name: "Malayalam"},
	{ code: "my", name: "Burmese"},
	{ code: "ps", name: "Pashto"},
	{ code: "sm", name: "Samoan"},
	{ code: "gd", name: "Scots Gaelic"},
	{ code: "st", name: "Sesotho"},
	{ code: "sn", name: "Shona"},
	{ code: "sd", name: "Sindhi"},
	{ code: "si", name: "Sinhala"},
	{ code: "su", name: "Sundanese"},
	{ code: "tg", name: "Tajik"},
	{ code: "uz", name: "Uzbek"},
	{ code: "xh", name: "Xhosa"},
	{ code: "yua", name: "Yucatec Maya"},
	{ code: "en-gb", name: "English (British)"},
	{ code: "es-la", name: "Spanish (Latin America)"},
	{ code: "pt-br", name: "Portuguese (Brazil)"},
	{ code: "fr-ca", name: "French (Canada)"}
];

//
// Copyright (c) Government of Western Australia -- Department of Health.
// https://www.healthywa.wa.gov.au/Healthy-living/Recipes/AZ-of-fruit
//
const TROPICAL_FRUITS = [
	{ code: "tf00000", name: "Apple"},
	{ code: "tf00005", name: "Apricot"},
	{ code: "tf00010", name: "Apricot lassi"},
	{ code: "tf00015", name: "Banana"},
	{ code: "tf00020", name: "Banana parcels"},
	{ code: "tf00025", name: "Banana toastie"},
	{ code: "tf00030", name: "Blueberry"},
	{ code: "tf00035", name: "Cherry"},
	{ code: "tf00040", name: "Custard apple or cherimoya"},
	{ code: "tf00045", name: "Durian"},
	{ code: "tf00050", name: "Feijoa"},
	{ code: "tf00055", name: "Fig"},
	{ code: "tf00060", name: "Fruity ice treats - Strawberry and kiwi & Tropical ice treats"},
	{ code: "tf00065", name: "Grape"},
	{ code: "tf00070", name: "Grapefruit"},
	{ code: "tf00075", name: "Grilled pineapple with star fruit"},
	{ code: "tf00080", name: "Guava"},
	{ code: "tf00085", name: "Honeydew"},
	{ code: "tf00090", name: "Kiwifruit"},
	{ code: "tf00095", name: "Lemon"},
	{ code: "tf00100", name: "Lime"},
	{ code: "tf00105", name: "Longan or dragon eyes"},
	{ code: "tf00110", name: "Lychee"},
	{ code: "tf00115", name: "Mandarin"},
	{ code: "tf00120", name: "Mango"},
	{ code: "tf00125", name: "Mangosteen"},
	{ code: "tf00130", name: "Melon platter"},
	{ code: "tf00135", name: "Nashi"},
	{ code: "tf00140", name: "Nectarine"},
	{ code: "tf00145", name: "Nectarine and berry salad"},
	{ code: "tf00150", name: "Orange"},
	{ code: "tf00155", name: "Passionfruit"},
	{ code: "tf00160", name: "Pawpaw wedges with lime"},
	{ code: "tf00165", name: "Pawpaw, papaw or papaya"},
	{ code: "tf00170", name: "Peach"},
	{ code: "tf00175", name: "Pear"},
	{ code: "tf00180", name: "Pear and banana muffins"},
	{ code: "tf00185", name: "Persimmon"},
	{ code: "tf00190", name: "Pineapple"},
	{ code: "tf00195", name: "Plum"},
	{ code: "tf00200", name: "Poached pears"},
	{ code: "tf00205", name: "Pomegranate"},
	{ code: "tf00210", name: "Pomelo, Chinese grapefruit or tropical citrus"},
	{ code: "tf00215", name: "Rambutan"},
	{ code: "tf00220", name: "Raspberry"},
	{ code: "tf00225", name: "Rhubarb"},
	{ code: "tf00230", name: "Rockmelon"},
	{ code: "tf00235", name: "Star fruit or carambola"},
	{ code: "tf00240", name: "Strawberry"},
	{ code: "tf00245", name: "Tamarillo or tree tomato"},
	{ code: "tf00250", name: "Tangelo"},
	{ code: "tf00255", name: "Watermelon"}
];